### ISSUE TITLE
Cloudflare API V1 will shutdown

### ISSUE THREAD

**Issue by solracsf** [blackdotsh/UptimeFlare#1]
https://blog.cloudflare.com/sunsetting-api-v1-in-favor-of-cloudflares-current-client-api-api-v4/

**Comment by blackdotsh** [comment]
I'm pretty busy this month but I'll look at it early next month to see if I can implement it. According to the blog I have until November 9th, 2016 so that should be plenty of time.

**Comment by solracsf** [comment]
Just for info ;)

**Comment by Nixtren** [comment]
We could also use this (or any other) CF API wrapper to avoid re-inventing the wheel:
https://packagist.org/packages/jamesryanbell/cloudflare

**Comment by blackdotsh** [comment]
I try to keep things minimal so I'm not going to include external packages even though it's easier for me code wise. 

I have recoded the cfBkup function to use CloudFlare's API v4. Let me know if you run into any issues.

**Comment by solracsf** [comment]
I'll test this ASAP, thanks :+1:
