### ISSUE TITLE
Problems with parsing HTTPS + www

### ISSUE THREAD

**Issue by conorbarclay** [blackdotsh/UptimeFlare#2]
We had issues with passing in URL's from UptimeRobot containing WWW and HTTPS...I think the current method of extracting the FQDN (line 130) is a bit too limiting and would suggest something more along these lines, which we currently have working for us:

`$url = urldecode($_GET['monitorURL']);`
`$checkDomain = implode('/', array_slice(explode('/', preg_replace('/https?:\/\/|www./', '', $url)), 0, 1));`

More suggestions would be great.

**Comment by blackdotsh** [comment]
https://github.com/blackdotsh/UptimeFlare/commit/169eedc98ea1e0ad5f97f9df9f78b7ef6f139810

Thanks :)
